# -*- coding: utf-8 -*-
"""Добро пожаловать в Colaboratory!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from itertools import product

!pip install pymorphy2
import pymorphy2

import string

d = dict()
with open("raw.githubusercontent.com_danakt_russian-words_master_russian.txt", encoding="cp1251") as file:
    for line in file:
        d[line[:-1]] = 1

msg = "одолжение домик лента стержень клен линолеум"
words = msg.translate(str.maketrans('', '', string.punctuation)).split()
letter_lists = [list(word) for word in words]
combinations = list(product(*letter_lists))
concatenated_combinations = [''.join(combination) for combination in combinations]

def is_meaningful_russian_word(word):
  return d.get(word) != None

results = []
llll = [0, 1, 6, 4, 7, 1, 5, 2, 4, 6, 2, 6, 6]
lengthy = [0, 1, 7, 11, 18, 19, 24, 26, 30, 36, 38, 44, 50]
lengths = [0, 10]
for x in concatenated_combinations:
  i = 1
  for y in range(0, len(lengths) - 1):
    if is_meaningful_russian_word(x[lengths[y]:lengths[y+1]]):
      i = i - 1
  if i == 0:
    results.append(x)

results